### ISSUE TITLE
alac patch failure

### ISSUE THREAD

**Issue by milkmiruku** [stsaz/ff-3pt#1]
A zsh `git am **/*.patch` gives (for 0001-Decode-don-t-set-output-sample-number-if-nothing-was.patch);

```
Applying: Decode(): don't set output sample number if nothing was decoded
error: codec/ALACDecoder.cpp: does not exist in index
```

**Comment by stsaz** [comment]
Hi!
Try using `cat {FF3PT}/{LIB}/*.patch | patch -p1` command instead.

`git am` will only work if you have an initialized git repository (e.g. to make more patches or amend patches).
If you want to use git for the first time, you need these commands:
```
git init
git add ./*
git commit -m initial
```

**Comment by milkmiruku** [comment]
Hmm, I get `zsh: no matches found: {FF3PT}/{LIB}/*.patch` for that (and `cat: '{FF-3PT}/{LIB}/*.patch': No such file or directory` in bash/sh), which is why I tried the zsh glob.

It is a git repo (I'm following the instructions for fmedia).

**Comment by stsaz** [comment]
I don't recommend building ff-3pt libs by yourself, because it's way too difficult for an unexperienced user.  If you want to build 3pt libs yourself you should download the official sources from the library developers' website and compile it separately.  ff-3pt repo contains only makefiles and patches - there's no actual code of those libraries.  The complex method of building 3pt libs allows not to depend on system libraries and make fmedia portable on every platform.

It's better if you download binaries for your platform from `releases` tab (the latest version of ff-3pt is v18.03).
Also, there are binaries for fmedia that you can download from fmedia website.  You generally don't need to build it yourself unless you're going to develop new features or fix bugs.

**Comment by milkmiruku** [comment]
> ff-3pt repo contains only makefiles and patches

A-ha, thanks for the clarification :)

Might you have a programmatic method of reproducing the build?

I was looking to create an Arch Linux PKGBUILD for fmedia. From a general perspective, a vcs (rather than bin) PKGBUILD is easier because the package version can be taken [automatically](https://wiki.archlinux.org/index.php/VCS_package_guidelines#Git) from the git repo (on install), where as bin PKGBUILDs need to be manually updated by the maintainer (or edited by the user) for each new release.

But if you're not building for the latest versions of libraries (targeted by rolling release distros), might you be using distro source packages? Arch might have source or bin versions (mostly in the AUR) available that sometimes relate to other distros or such.

Might the use of git submodules to retrieving library code be something you would be interested in? It could be done recursively from the fmedia repo.

Here's my [initial PKGBUILD](https://gist.github.com/milkmiruku/6683e6ad15ee66a03eec1c90a31a80f5) without moving/patching, just went through with the specific versions, I'll come back to that over the next few days. Already I noticed flac dep. matches the Arch Extra repos version so the source could be copied. I might make a binary version to, for kicks/experience.
